version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=rimi
      - POSTGRES_PASSWORD=1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  web:
    build: .
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/web
    depends_on:
      - db
