version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=modeling
      - POSTGRES_USER=rimi
      - POSTGRES_PASSWORD=1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
    - "5432:5432"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=modeling
      - DJANGO_DB_USERNAME=rimi
      - DJANGO_DB_PASSWORD=1234
      - DJANGO_SECRET_KEY=dtn96mf%5x_x1&2_u1dvuo#7h5zz4w!(!jfqh48t-l=ttz%_90
    ports:
      - "8000:8000"
    command:
      - python
      - manage.py
      - runserver
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./:/app/