# Generated by Django 3.1 on 2020-08-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cars_count',
            field=models.ManyToManyField(blank=True, through='common.CompanyCarCount', to='common.Car'),
        ),
    ]
